import type { Metadata } from "next";
import { Inter_Tight, Albert_Sans, Galada } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from 'next/image'
import Footer from "@/components/ui/footer";

const interTight = Inter_Tight({
  variable: "--font-inter-tight",
  subsets: ["latin"],
});

const albertSans = Albert_Sans({
  variable: "--font-albert-sans",
  subsets: ["latin"],
});

const galada = Galada({
  variable: "--font-galada",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interTight.variable} ${albertSans.variable} ${galada.variable} flex flex-col mx-auto w-full max-w-[1920px] antialiased box-border`}
      >
        {children}
        {/* Uncover unique destinations */}
        <section className="relative w-full h-[700px] flex flex-col items-center justify-center text-white p-3.5 md:p-4">
          <Image
            className="p-4 rounded-4xl md:rounded-[48px] -z-10"
            src='/uncover-unique.jpg'
            alt=""
            objectFit="cover"
            objectPosition="center"
            fill
          />
          <div className="flex flex-col items-center justify-center font-albert-sans gap-8 max-w-[1074px] mx-4 md:mx-10">
            <h2 className="text-4xl md:text-6xl xl:text-7xl font-semibold text-center leading-tight">Uncover unique destinations tailored just for you by Ar Rahah</h2>
            <p className="font-medium text-lg text-center md:mx-18 lg:mx-32">Lorem ipsum dolor sit amet consectetur. Ac turpis et amet facilisis purus egestas enim ante. Porttitor nunc semper nunc libero vitae eget. Odio ultricies ornare tristique in erat auctor tellus</p>
            <Link href='/' className='w-full md:w-fit h-fit row-start-2 md:col-start-1 lg:col-start-2 md:row-start-2 md:row-end-3 lg:row-start-1 lg:row-end-2 justify-self-end flex flex-row items-center justify-center gap-2 px-8 py-3 md:py-6 bg-white text-black text-lg font-semibold rounded-full'>
              <span>Book Trip to Turkey</span>
              <img className='w-[1.5em] h-fit' src='/black-triple-chevron.svg' />
            </Link>
          </div>
        </section>
        {/* footer */}
        <Footer />
      </body>
    </html>
  );
}
