import type { Metadata } from "next";
import { Inter_Tight, Albert_Sans, Galada } from "next/font/google";
import "./globals.css";
import Footer from "@/components/ui/footer";

const interTight = Inter_Tight({
  variable: "--font-inter-tight",
  subsets: ["latin"],
});

const albertSans = Albert_Sans({
  variable: "--font-albert-sans",
  subsets: ["latin"],
});

const galada = Galada({
  variable: "--font-galada",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interTight.variable} ${albertSans.variable} ${galada.variable} flex flex-col mx-auto w-full antialiased box-border`}
      >
        {children}
        {/* Uncover unique destinations */}
        {/* footer */}
        <Footer />
      </body>
    </html>
  );
}
